### ISSUE TITLE
please help: ValueError: Dimension 0 in both shapes must be equal, but are 73 and 72. Shapes are [73,1024] and [72,1024]. for 'Assign' (op: 'Assign') with input shapes: [73,1024], [72,1024].

### ISSUE THREAD

**Issue by JuanERombado** [571530/RapGenerator#1]
(tensorflow_p36) [ec2-user@ip-172-31-31-58 RapGenerator-master]$ python train.py
Using TensorFlow backend.
Reading lyrics
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    network.train_network('weights.h5')
  File "/home/ec2-user/RapGenerator-master2/RapGenerator-master/network.py", line 101, in train_network
    text, chars, char_indices, indices_char = get_data('data/lyrics.txt')
  File "/home/ec2-user/RapGenerator-master2/RapGenerator-master/network.py", line 20, in get_data
    text = open(filepath).read().lower()
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 20480: invalid continuation byte
(tensorflow_p36) [ec2-user@ip-172-31-31-58 RapGenerator-master]$ python train.py
Using TensorFlow backend.
Reading lyrics
Preparing data
Creating model
WARNING:tensorflow:From /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 73 and 72. Shapes are [73,1024] and [72,1024]. for 'Assign' (op: 'Assign') with input shapes: [73,1024], [72,1024].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 4, in <module>
    network.train_network('weights.h5')
  File "/home/ec2-user/RapGenerator-master2/RapGenerator-master/network.py", line 114, in train_network
    model.load_weights(weights)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/engine/saving.py", line 1058, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2465, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 1762, in assign
    name=name)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 64, in assign
    use_locking=use_locking, name=name)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 73 and 72. Shapes are [73,1024] and [72,1024]. for 'Assign' (op: 'Assign') with input shapes: [73,1024], [72,1024].

**Comment by JuanERombado** [comment]
i think i need to use different weights maybe. im new to this

**Comment by JuanERombado** [comment]
if i remove the weights and leave it empty, it works. hmm
